# Dependencies
markdown:         redcarpet
highlighter:      pygments

redcarpet:
    extensions: [with_toc_data]

# Permalinks
#permalink:        pretty
permalink:  "/posts/:title"
relative_permalinks: true

# Setup
title:            flatline security
tagline:          ''
description:      ''
url:              https://flatlinesecurity.com
baseurl:          /

author:
  name:           'curtis'
  url:            https://flatlinesecurity.com

paginate:         5
